<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DisasterResourceAllocation.Domain\DisasterResourceAllocation.Domain.csproj" />
    <ProjectReference Include="..\DisasterResourceAllocation.Application\DisasterResourceAllocation.Application.csproj" />
  </ItemGroup>

</Project>