<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\DisasterResourceAllocation.Domain.csproj" />
    <ProjectReference Include="..\Application\DisasterResourceAllocation.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\DisasterResourceAllocation.Infrastructure.csproj" />
  </ItemGroup>

</Project>